# Generated by Django 2.2 on 2019-11-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191101_1151'),
    ]

    operations = [
    ]
