# Generated by Django 2.2 on 2019-11-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191101_1232'),
    ]

    operations = [
    ]
