# Generated by Django 2.2 on 2019-11-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191103_1712'),
    ]

    operations = [
    ]
