# Generated by Django 2.2 on 2019-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of completion'),
        ),
    ]
