# Generated by Django 2.2 on 2019-11-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191103_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
