# Generated by Django 2.2 on 2019-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='site'),
        ),
    ]
