# Generated by Django 2.2 on 2019-11-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
    ]
