# Generated by Django 2.2 on 2019-10-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description project')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Time updated')),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracker', to='webapp.Project', verbose_name='Project'),
        ),
    ]
