# Generated by Django 2.2 on 2019-10-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191008_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracker', to='webapp.Project', verbose_name='Project'),
        ),
    ]
