# Generated by Django 2.2 on 2019-11-11 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_tracker_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('admin', 'Admin'), ('author', 'Author')], max_length=20, verbose_name='role')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date of completion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_user', to='webapp.Project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
